### ISSUE TITLE
can't dismiss

### ISSUE THREAD

**Issue by n2waf** [EgzonArifi/EAAlertView#1]
hello 
there is problem with me when i try to dismiss 
there is nothing happening 
and the dismiss method does not work
`     

       let picker = UIDatePicker(frame: CGRect(x: 0, y: 0, width: self.view.frame.width*0.8, height: 200))
        picker.datePickerMode = UIDatePicker.Mode.date
        
        let appearance = EAAlertView.EAAppearance(kButtonHeight: 60, showCloseButton: false, shouldAutoDismiss: false)
        let alert = EAAlertView(appearance: appearance)
        alert.customSubview = picker
        
        alert.addButton("ok") {
            alert.dismiss(animated: false, completion: {
                print("dismissed")
            })
        }
          alert.show("Birthdate", subTitle: " ") `

**Comment by EgzonArifi** [comment]
Hi @n2waf, thank you for using my library. To dismiss alert you should use `alert.hideView()`

   ```
let picker = UIDatePicker(frame: CGRect(x: 0, y: 0, width: self.view.frame.width*0.8, height: 200))
    picker.datePickerMode = UIDatePicker.Mode.date
    
    let appearance = EAAlertView.EAAppearance(kButtonHeight: 60, showCloseButton: false, shouldAutoDismiss: false)
    let alert = EAAlertView(appearance: appearance)
    alert.customSubview = picker
    
    alert.addButton("ok") {
        alert.hideView()
    }
   alert.show("Birthdate", subTitle: " ")
```

**Comment by n2waf** [comment]
Thank u man it’s worked !! 
Can u add that in readme ? Maybe someone doesn’t know

**Comment by EgzonArifi** [comment]
Sure, I'll add it and close this issue
